#!/bin/bash

if [ -z "$MODE" ]; then
    echo "MODE variable must be set"
    exit 1
fi

# setup connection url
RABBITMQ_USERNAME=rabbitmq
RABBITMQ_PASSWORD=Welcome1
RABBITMQ_VHOST=${RABBITMQ_VHOST:-/%2F}
RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME:-rabbit2}
RABBITMQ_PORT=5672
RABBITMQ_PROTOCOL=amqp
RABBITMQ_EXTRA_PARAMS='?heartbeat_interval=60'

export RABBITMQ_USERNAME RABBITMQ_PASSWORD RABBITMQ_VHOST RABBITMQ_HOSTNAME RABBITMQ_PORT RABBITMQ_PROTOCOL RABBITMQ_EXTRA_PARAMS

exec "$@" /scripts/$MODE.py
